version: 1

formatters:
  json:
    (): services.api_logging.config_logging.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/pipeline.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
root:
  level: DEBUG
  handlers: [console, file]

loggers:
  aiocache:
    level: INFO
    propagate: true

  urllib3:
    level: INFO
    propagate: true

  openai:
    level: WARNING
    propagate: true

  httpx:
    level: WARNING
    propagate: true

  httpcore:
    level: WARNING
    propagate: true

  charset_normalizer:
    level: WARNING
    propagate: true

  azure:
    level: WARNING
    propagate: true

disable_existing_loggers: false