version: 1
formatters:
  default:
    format: 'Timestamp=%(asctime)s Level=%(levelname)s AppName=%(app_name_field)s Logger=%(name)s Message=%(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S.%3N%z'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
root:
  # THis will be changed by the environment variable anyway
  level: DEBUG
  handlers: [console]
loggers:
  streamlit:
    level: DEBUG
    propagate: true
  streamlit.web.server.media_file_handler:
    level: INFO
    propagate: true
disable_existing_loggers: false