# =============================================================================
# config.yaml — Backend table configurations
# =============================================================================
tables:
  schema: container
  staging: #output from api calls is saved 
    est_raw:    m4_api_est_imgs    # one row per estimate
    est_line:  m4_api_est_line     # one row per line item
    est_subtot: m4_api_est_subtot   # one row per subtotal
  vi_output:
    folders_table:      m4_vi_estimate_results
    images_table:       m4_vi_image_results
  em_output:
    line_detail:   m4_em_est_line_dtl
    subtot_detail: m4_em_est_subtot_dtl
    est_summary:   m4_em_est_summary
    overall_summary: m4_est_overall_results
