trigger: none

pr:
  branches:
    include: [main]
  paths:
    include: [src/backend/*]

jobs:
  - job: BackendChecks
    pool: VO Pool
    workspace:
      clean: all
    steps:
      - script: |
          set -e
          cd src/backend
          python3 -m venv $(Pipeline.Workspace)/.venv
          source $(Pipeline.Workspace)/.venv/bin/activate
          pip install -r requirements/requirements.txt
        displayName: 'Setup venv'
      - script: |
          set -e
          cd src/backend
          source $(Pipeline.Workspace)/.venv/bin/activate
          make lint
        displayName: 'Backend lint'
        condition: succeededOrFailed()
      - script: |
          set -e
          cd src/backend
          source $(Pipeline.Workspace)/.venv/bin/activate
          make format-check
        displayName: 'Backend check format'
        condition: succeededOrFailed()
      - script: |
          set -e
          cd src/backend
          source $(Pipeline.Workspace)/.venv/bin/activate
          make python-sast
        displayName: 'Backend sast'
        condition: succeededOrFailed()
